<?="<?php\n"?>
/**
 * This file is automatically generated from the database schema by:
 * https://github.com/MarQuisKnox/Zend_Db-model-generator
 *
 * @author      <?=$this->_author."\n"?>
 * @copyright   <?=$this->_copyright."\n"?>
 * @license     <?=$this->_license."\n"?>
 *
 * @uses        <?=$this->_namespace?>_Generated_Model_<?=$this->_className?>
 <?="\n"?>
 */

<? if ($this->_addRequire): ?>
require_once('Generated/<?=$this->_namespace?>_Generated_Model_<?=$this->_className?>.php');
<? endif; ?>

class <?=$this->_namespace?>_Model_<?=$this->_className?> extends <?=$this->_namespace?>_Generated_Model_<?=$this->_className?>
<?="\n"?>
{
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * add your custom code here
     */
}